# Generated by Django 5.2.8 on 2025-11-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_specialinterest_tooltechnology_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
